// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatEmojiStatus Chat emoji status has changed
type UpdateChatEmojiStatus struct {
	Filter   filters.UpdateChatEmojiStatus
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatEmojiStatus) error
}

// NewUpdateChatEmojiStatus creates a new UpdateChatEmojiStatus
func NewUpdateChatEmojiStatus(filter filters.UpdateChatEmojiStatus, response func(b *gotdbot.Client, u *gotdbot.UpdateChatEmojiStatus) error) *UpdateChatEmojiStatus {
	return &UpdateChatEmojiStatus{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatEmojiStatus) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatEmojiStatus)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatEmojiStatus) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatEmojiStatus))
}
