// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatIsMarkedAsUnread A chat was marked as unread or was read
type UpdateChatIsMarkedAsUnread struct {
	Filter   filters.UpdateChatIsMarkedAsUnread
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatIsMarkedAsUnread) error
}

// NewUpdateChatIsMarkedAsUnread creates a new UpdateChatIsMarkedAsUnread
func NewUpdateChatIsMarkedAsUnread(filter filters.UpdateChatIsMarkedAsUnread, response func(b *gotdbot.Client, u *gotdbot.UpdateChatIsMarkedAsUnread) error) *UpdateChatIsMarkedAsUnread {
	return &UpdateChatIsMarkedAsUnread{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatIsMarkedAsUnread) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatIsMarkedAsUnread)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatIsMarkedAsUnread) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatIsMarkedAsUnread))
}
