// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGroupCallMessagesDeleted Some group call messages were deleted
type UpdateGroupCallMessagesDeleted struct {
	Filter   filters.UpdateGroupCallMessagesDeleted
	Response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCallMessagesDeleted) error
}

// NewUpdateGroupCallMessagesDeleted creates a new UpdateGroupCallMessagesDeleted
func NewUpdateGroupCallMessagesDeleted(filter filters.UpdateGroupCallMessagesDeleted, response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCallMessagesDeleted) error) *UpdateGroupCallMessagesDeleted {
	return &UpdateGroupCallMessagesDeleted{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallMessagesDeleted) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateGroupCallMessagesDeleted)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallMessagesDeleted) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateGroupCallMessagesDeleted))
}
