// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateOption An option changed its value
type UpdateOption struct {
	Filter   filters.UpdateOption
	Response func(b *gotdbot.Client, u *gotdbot.UpdateOption) error
}

// NewUpdateOption creates a new UpdateOption
func NewUpdateOption(filter filters.UpdateOption, response func(b *gotdbot.Client, u *gotdbot.UpdateOption) error) *UpdateOption {
	return &UpdateOption{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateOption) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateOption)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateOption) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateOption))
}
