// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewShippingQuery A new incoming shipping query; for bots only. Only for invoices with flexible price
type UpdateNewShippingQuery struct {
	Filter   filters.UpdateNewShippingQuery
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewShippingQuery) error
}

// NewUpdateNewShippingQuery creates a new UpdateNewShippingQuery
func NewUpdateNewShippingQuery(filter filters.UpdateNewShippingQuery, response func(b *gotdbot.Client, u *gotdbot.UpdateNewShippingQuery) error) *UpdateNewShippingQuery {
	return &UpdateNewShippingQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewShippingQuery) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewShippingQuery)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewShippingQuery) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewShippingQuery))
}
