// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatFolders The list of chat folders or a chat folder has changed
type UpdateChatFolders struct {
	Filter   filters.UpdateChatFolders
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatFolders) error
}

// NewUpdateChatFolders creates a new UpdateChatFolders
func NewUpdateChatFolders(filter filters.UpdateChatFolders, response func(b *gotdbot.Client, u *gotdbot.UpdateChatFolders) error) *UpdateChatFolders {
	return &UpdateChatFolders{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatFolders) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatFolders)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatFolders) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatFolders))
}
