// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateBusinessConnection A business connection has changed; for bots only
type UpdateBusinessConnection struct {
	Filter   filters.UpdateBusinessConnection
	Response func(b *gotdbot.Client, u *gotdbot.UpdateBusinessConnection) error
}

// NewUpdateBusinessConnection creates a new UpdateBusinessConnection
func NewUpdateBusinessConnection(filter filters.UpdateBusinessConnection, response func(b *gotdbot.Client, u *gotdbot.UpdateBusinessConnection) error) *UpdateBusinessConnection {
	return &UpdateBusinessConnection{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateBusinessConnection) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateBusinessConnection)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateBusinessConnection) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateBusinessConnection))
}
