// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewCustomEvent A new incoming event; for bots only
type UpdateNewCustomEvent struct {
	Filter   filters.UpdateNewCustomEvent
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewCustomEvent) error
}

// NewUpdateNewCustomEvent creates a new UpdateNewCustomEvent
func NewUpdateNewCustomEvent(filter filters.UpdateNewCustomEvent, response func(b *gotdbot.Client, u *gotdbot.UpdateNewCustomEvent) error) *UpdateNewCustomEvent {
	return &UpdateNewCustomEvent{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewCustomEvent) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewCustomEvent)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewCustomEvent) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewCustomEvent))
}
