// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateDefaultPaidReactionType The type of default paid reaction has changed
type UpdateDefaultPaidReactionType struct {
	Filter   filters.UpdateDefaultPaidReactionType
	Response func(b *gotdbot.Client, u *gotdbot.UpdateDefaultPaidReactionType) error
}

// NewUpdateDefaultPaidReactionType creates a new UpdateDefaultPaidReactionType
func NewUpdateDefaultPaidReactionType(filter filters.UpdateDefaultPaidReactionType, response func(b *gotdbot.Client, u *gotdbot.UpdateDefaultPaidReactionType) error) *UpdateDefaultPaidReactionType {
	return &UpdateDefaultPaidReactionType{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateDefaultPaidReactionType) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateDefaultPaidReactionType)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateDefaultPaidReactionType) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateDefaultPaidReactionType))
}
