// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGroupCallVerificationState The verification state of an encrypted group call has changed; for group calls not bound to a chat only
type UpdateGroupCallVerificationState struct {
	Filter   filters.UpdateGroupCallVerificationState
	Response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCallVerificationState) error
}

// NewUpdateGroupCallVerificationState creates a new UpdateGroupCallVerificationState
func NewUpdateGroupCallVerificationState(filter filters.UpdateGroupCallVerificationState, response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCallVerificationState) error) *UpdateGroupCallVerificationState {
	return &UpdateGroupCallVerificationState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallVerificationState) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateGroupCallVerificationState)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallVerificationState) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateGroupCallVerificationState))
}
