// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateQuickReplyShortcuts The list of quick reply shortcuts has changed
type UpdateQuickReplyShortcuts struct {
	Filter   filters.UpdateQuickReplyShortcuts
	Response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcuts) error
}

// NewUpdateQuickReplyShortcuts creates a new UpdateQuickReplyShortcuts
func NewUpdateQuickReplyShortcuts(filter filters.UpdateQuickReplyShortcuts, response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcuts) error) *UpdateQuickReplyShortcuts {
	return &UpdateQuickReplyShortcuts{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateQuickReplyShortcuts) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateQuickReplyShortcuts)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateQuickReplyShortcuts) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateQuickReplyShortcuts))
}
