// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateOwnedTonCount The number of Toncoins owned by the current user has changed
type UpdateOwnedTonCount struct {
	Filter   filters.UpdateOwnedTonCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateOwnedTonCount) error
}

// NewUpdateOwnedTonCount creates a new UpdateOwnedTonCount
func NewUpdateOwnedTonCount(filter filters.UpdateOwnedTonCount, response func(b *gotdbot.Client, u *gotdbot.UpdateOwnedTonCount) error) *UpdateOwnedTonCount {
	return &UpdateOwnedTonCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateOwnedTonCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateOwnedTonCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateOwnedTonCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateOwnedTonCount))
}
