// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateStoryStealthMode Story stealth mode settings have changed
type UpdateStoryStealthMode struct {
	Filter   filters.UpdateStoryStealthMode
	Response func(b *gotdbot.Client, u *gotdbot.UpdateStoryStealthMode) error
}

// NewUpdateStoryStealthMode creates a new UpdateStoryStealthMode
func NewUpdateStoryStealthMode(filter filters.UpdateStoryStealthMode, response func(b *gotdbot.Client, u *gotdbot.UpdateStoryStealthMode) error) *UpdateStoryStealthMode {
	return &UpdateStoryStealthMode{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStoryStealthMode) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateStoryStealthMode)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStoryStealthMode) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateStoryStealthMode))
}
