// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageUnreadReactions The list of unread reactions added to a message was changed
type UpdateMessageUnreadReactions struct {
	Filter   filters.UpdateMessageUnreadReactions
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageUnreadReactions) error
}

// NewUpdateMessageUnreadReactions creates a new UpdateMessageUnreadReactions
func NewUpdateMessageUnreadReactions(filter filters.UpdateMessageUnreadReactions, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageUnreadReactions) error) *UpdateMessageUnreadReactions {
	return &UpdateMessageUnreadReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageUnreadReactions) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageUnreadReactions)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageUnreadReactions) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageUnreadReactions))
}
