// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateStoryListChatCount Number of chats in a story list has changed
type UpdateStoryListChatCount struct {
	Filter   filters.UpdateStoryListChatCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateStoryListChatCount) error
}

// NewUpdateStoryListChatCount creates a new UpdateStoryListChatCount
func NewUpdateStoryListChatCount(filter filters.UpdateStoryListChatCount, response func(b *gotdbot.Client, u *gotdbot.UpdateStoryListChatCount) error) *UpdateStoryListChatCount {
	return &UpdateStoryListChatCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStoryListChatCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateStoryListChatCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStoryListChatCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateStoryListChatCount))
}
