// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateManagedBot A bot that can be managed by the current bot was created or updated; for bots only
type UpdateManagedBot struct {
	Filter   filters.UpdateManagedBot
	Response func(b *gotdbot.Client, u *gotdbot.UpdateManagedBot) error
}

// NewUpdateManagedBot creates a new UpdateManagedBot
func NewUpdateManagedBot(filter filters.UpdateManagedBot, response func(b *gotdbot.Client, u *gotdbot.UpdateManagedBot) error) *UpdateManagedBot {
	return &UpdateManagedBot{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateManagedBot) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateManagedBot)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateManagedBot) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateManagedBot))
}
