// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageReactions Reactions added to a message with anonymous reactions have changed; for bots only
type UpdateMessageReactions struct {
	Filter   filters.UpdateMessageReactions
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageReactions) error
}

// NewUpdateMessageReactions creates a new UpdateMessageReactions
func NewUpdateMessageReactions(filter filters.UpdateMessageReactions, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageReactions) error) *UpdateMessageReactions {
	return &UpdateMessageReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageReactions) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageReactions)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageReactions) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageReactions))
}
