// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageSuggestedPostInfo Information about suggested post of a message was changed
type UpdateMessageSuggestedPostInfo struct {
	Filter   filters.UpdateMessageSuggestedPostInfo
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSuggestedPostInfo) error
}

// NewUpdateMessageSuggestedPostInfo creates a new UpdateMessageSuggestedPostInfo
func NewUpdateMessageSuggestedPostInfo(filter filters.UpdateMessageSuggestedPostInfo, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSuggestedPostInfo) error) *UpdateMessageSuggestedPostInfo {
	return &UpdateMessageSuggestedPostInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSuggestedPostInfo) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageSuggestedPostInfo)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSuggestedPostInfo) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageSuggestedPostInfo))
}
