// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateLiveStoryTopDonors The list of top donors in live story group call has changed
type UpdateLiveStoryTopDonors struct {
	Filter   filters.UpdateLiveStoryTopDonors
	Response func(b *gotdbot.Client, u *gotdbot.UpdateLiveStoryTopDonors) error
}

// NewUpdateLiveStoryTopDonors creates a new UpdateLiveStoryTopDonors
func NewUpdateLiveStoryTopDonors(filter filters.UpdateLiveStoryTopDonors, response func(b *gotdbot.Client, u *gotdbot.UpdateLiveStoryTopDonors) error) *UpdateLiveStoryTopDonors {
	return &UpdateLiveStoryTopDonors{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateLiveStoryTopDonors) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateLiveStoryTopDonors)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateLiveStoryTopDonors) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateLiveStoryTopDonors))
}
