// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateStory A story was changed
type UpdateStory struct {
	Filter   filters.UpdateStory
	Response func(b *gotdbot.Client, u *gotdbot.UpdateStory) error
}

// NewUpdateStory creates a new UpdateStory
func NewUpdateStory(filter filters.UpdateStory, response func(b *gotdbot.Client, u *gotdbot.UpdateStory) error) *UpdateStory {
	return &UpdateStory{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStory) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateStory)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStory) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateStory))
}
