// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAvailableMessageEffects The list of available message effects has changed
type UpdateAvailableMessageEffects struct {
	Filter   filters.UpdateAvailableMessageEffects
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAvailableMessageEffects) error
}

// NewUpdateAvailableMessageEffects creates a new UpdateAvailableMessageEffects
func NewUpdateAvailableMessageEffects(filter filters.UpdateAvailableMessageEffects, response func(b *gotdbot.Client, u *gotdbot.UpdateAvailableMessageEffects) error) *UpdateAvailableMessageEffects {
	return &UpdateAvailableMessageEffects{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAvailableMessageEffects) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAvailableMessageEffects)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAvailableMessageEffects) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAvailableMessageEffects))
}
