// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageSendAcknowledged A request to send a message has reached the Telegram server. This doesn't mean that the message will be sent successfully.
type UpdateMessageSendAcknowledged struct {
	Filter   filters.UpdateMessageSendAcknowledged
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSendAcknowledged) error
}

// NewUpdateMessageSendAcknowledged creates a new UpdateMessageSendAcknowledged
func NewUpdateMessageSendAcknowledged(filter filters.UpdateMessageSendAcknowledged, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSendAcknowledged) error) *UpdateMessageSendAcknowledged {
	return &UpdateMessageSendAcknowledged{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSendAcknowledged) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageSendAcknowledged)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSendAcknowledged) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageSendAcknowledged))
}
