// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatBoost A chat boost has changed; for bots only
type UpdateChatBoost struct {
	Filter   filters.UpdateChatBoost
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatBoost) error
}

// NewUpdateChatBoost creates a new UpdateChatBoost
func NewUpdateChatBoost(filter filters.UpdateChatBoost, response func(b *gotdbot.Client, u *gotdbot.UpdateChatBoost) error) *UpdateChatBoost {
	return &UpdateChatBoost{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatBoost) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatBoost)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatBoost) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatBoost))
}
