// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAnimationSearchParameters The parameters of animation search through getOption("animation_search_bot_username") bot has changed
type UpdateAnimationSearchParameters struct {
	Filter   filters.UpdateAnimationSearchParameters
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAnimationSearchParameters) error
}

// NewUpdateAnimationSearchParameters creates a new UpdateAnimationSearchParameters
func NewUpdateAnimationSearchParameters(filter filters.UpdateAnimationSearchParameters, response func(b *gotdbot.Client, u *gotdbot.UpdateAnimationSearchParameters) error) *UpdateAnimationSearchParameters {
	return &UpdateAnimationSearchParameters{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAnimationSearchParameters) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAnimationSearchParameters)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAnimationSearchParameters) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAnimationSearchParameters))
}
