// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatDefaultDisableNotification The value of the default disable_notification parameter, used when a message is sent to the chat, was changed
type UpdateChatDefaultDisableNotification struct {
	Filter   filters.UpdateChatDefaultDisableNotification
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatDefaultDisableNotification) error
}

// NewUpdateChatDefaultDisableNotification creates a new UpdateChatDefaultDisableNotification
func NewUpdateChatDefaultDisableNotification(filter filters.UpdateChatDefaultDisableNotification, response func(b *gotdbot.Client, u *gotdbot.UpdateChatDefaultDisableNotification) error) *UpdateChatDefaultDisableNotification {
	return &UpdateChatDefaultDisableNotification{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatDefaultDisableNotification) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatDefaultDisableNotification)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatDefaultDisableNotification) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatDefaultDisableNotification))
}
