// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFile Information about a file was updated
type UpdateFile struct {
	Filter   filters.UpdateFile
	Response func(b *gotdbot.Client, u *gotdbot.UpdateFile) error
}

// NewUpdateFile creates a new UpdateFile
func NewUpdateFile(filter filters.UpdateFile, response func(b *gotdbot.Client, u *gotdbot.UpdateFile) error) *UpdateFile {
	return &UpdateFile{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFile) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateFile)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFile) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateFile))
}
