// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSupergroupFullInfo Some data in supergroupFullInfo has been changed
type UpdateSupergroupFullInfo struct {
	Filter   filters.UpdateSupergroupFullInfo
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSupergroupFullInfo) error
}

// NewUpdateSupergroupFullInfo creates a new UpdateSupergroupFullInfo
func NewUpdateSupergroupFullInfo(filter filters.UpdateSupergroupFullInfo, response func(b *gotdbot.Client, u *gotdbot.UpdateSupergroupFullInfo) error) *UpdateSupergroupFullInfo {
	return &UpdateSupergroupFullInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSupergroupFullInfo) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSupergroupFullInfo)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSupergroupFullInfo) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSupergroupFullInfo))
}
