// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatHasScheduledMessages A chat's has_scheduled_messages field has changed
type UpdateChatHasScheduledMessages struct {
	Filter   filters.UpdateChatHasScheduledMessages
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatHasScheduledMessages) error
}

// NewUpdateChatHasScheduledMessages creates a new UpdateChatHasScheduledMessages
func NewUpdateChatHasScheduledMessages(filter filters.UpdateChatHasScheduledMessages, response func(b *gotdbot.Client, u *gotdbot.UpdateChatHasScheduledMessages) error) *UpdateChatHasScheduledMessages {
	return &UpdateChatHasScheduledMessages{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatHasScheduledMessages) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatHasScheduledMessages)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatHasScheduledMessages) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatHasScheduledMessages))
}
