// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAttachmentMenuBots The list of bots added to attachment or side menu has changed
type UpdateAttachmentMenuBots struct {
	Filter   filters.UpdateAttachmentMenuBots
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAttachmentMenuBots) error
}

// NewUpdateAttachmentMenuBots creates a new UpdateAttachmentMenuBots
func NewUpdateAttachmentMenuBots(filter filters.UpdateAttachmentMenuBots, response func(b *gotdbot.Client, u *gotdbot.UpdateAttachmentMenuBots) error) *UpdateAttachmentMenuBots {
	return &UpdateAttachmentMenuBots{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAttachmentMenuBots) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAttachmentMenuBots)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAttachmentMenuBots) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAttachmentMenuBots))
}
