// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatReplyMarkup The chat reply markup was changed
type UpdateChatReplyMarkup struct {
	Filter   filters.UpdateChatReplyMarkup
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatReplyMarkup) error
}

// NewUpdateChatReplyMarkup creates a new UpdateChatReplyMarkup
func NewUpdateChatReplyMarkup(filter filters.UpdateChatReplyMarkup, response func(b *gotdbot.Client, u *gotdbot.UpdateChatReplyMarkup) error) *UpdateChatReplyMarkup {
	return &UpdateChatReplyMarkup{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatReplyMarkup) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatReplyMarkup)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatReplyMarkup) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatReplyMarkup))
}
