// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateDefaultReactionType The type of default reaction has changed
type UpdateDefaultReactionType struct {
	Filter   filters.UpdateDefaultReactionType
	Response func(b *gotdbot.Client, u *gotdbot.UpdateDefaultReactionType) error
}

// NewUpdateDefaultReactionType creates a new UpdateDefaultReactionType
func NewUpdateDefaultReactionType(filter filters.UpdateDefaultReactionType, response func(b *gotdbot.Client, u *gotdbot.UpdateDefaultReactionType) error) *UpdateDefaultReactionType {
	return &UpdateDefaultReactionType{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateDefaultReactionType) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateDefaultReactionType)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateDefaultReactionType) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateDefaultReactionType))
}
