// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewCustomQuery A new incoming query; for bots only
type UpdateNewCustomQuery struct {
	Filter   filters.UpdateNewCustomQuery
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewCustomQuery) error
}

// NewUpdateNewCustomQuery creates a new UpdateNewCustomQuery
func NewUpdateNewCustomQuery(filter filters.UpdateNewCustomQuery, response func(b *gotdbot.Client, u *gotdbot.UpdateNewCustomQuery) error) *UpdateNewCustomQuery {
	return &UpdateNewCustomQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewCustomQuery) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewCustomQuery)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewCustomQuery) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewCustomQuery))
}
