// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatDraftMessage A chat draft has changed. Be aware that the update may come in the currently opened chat but with old content of the draft. If the user has changed the content of the draft, this update mustn't be applied
type UpdateChatDraftMessage struct {
	Filter   filters.UpdateChatDraftMessage
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatDraftMessage) error
}

// NewUpdateChatDraftMessage creates a new UpdateChatDraftMessage
func NewUpdateChatDraftMessage(filter filters.UpdateChatDraftMessage, response func(b *gotdbot.Client, u *gotdbot.UpdateChatDraftMessage) error) *UpdateChatDraftMessage {
	return &UpdateChatDraftMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatDraftMessage) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatDraftMessage)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatDraftMessage) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatDraftMessage))
}
