// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateApplicationRecaptchaVerificationRequired A request can't be completed unless reCAPTCHA verification is performed; for official mobile applications only.
type UpdateApplicationRecaptchaVerificationRequired struct {
	Filter   filters.UpdateApplicationRecaptchaVerificationRequired
	Response func(b *gotdbot.Client, u *gotdbot.UpdateApplicationRecaptchaVerificationRequired) error
}

// NewUpdateApplicationRecaptchaVerificationRequired creates a new UpdateApplicationRecaptchaVerificationRequired
func NewUpdateApplicationRecaptchaVerificationRequired(filter filters.UpdateApplicationRecaptchaVerificationRequired, response func(b *gotdbot.Client, u *gotdbot.UpdateApplicationRecaptchaVerificationRequired) error) *UpdateApplicationRecaptchaVerificationRequired {
	return &UpdateApplicationRecaptchaVerificationRequired{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateApplicationRecaptchaVerificationRequired) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateApplicationRecaptchaVerificationRequired)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateApplicationRecaptchaVerificationRequired) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateApplicationRecaptchaVerificationRequired))
}
