// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatActiveStories The list of active stories posted by a specific chat has changed
type UpdateChatActiveStories struct {
	Filter   filters.UpdateChatActiveStories
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatActiveStories) error
}

// NewUpdateChatActiveStories creates a new UpdateChatActiveStories
func NewUpdateChatActiveStories(filter filters.UpdateChatActiveStories, response func(b *gotdbot.Client, u *gotdbot.UpdateChatActiveStories) error) *UpdateChatActiveStories {
	return &UpdateChatActiveStories{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatActiveStories) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatActiveStories)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatActiveStories) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatActiveStories))
}
