// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatTheme The chat theme was changed
type UpdateChatTheme struct {
	Filter   filters.UpdateChatTheme
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatTheme) error
}

// NewUpdateChatTheme creates a new UpdateChatTheme
func NewUpdateChatTheme(filter filters.UpdateChatTheme, response func(b *gotdbot.Client, u *gotdbot.UpdateChatTheme) error) *UpdateChatTheme {
	return &UpdateChatTheme{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatTheme) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatTheme)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatTheme) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatTheme))
}
