// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewGroupCallMessage A new message was received in a group call
type UpdateNewGroupCallMessage struct {
	Filter   filters.UpdateNewGroupCallMessage
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewGroupCallMessage) error
}

// NewUpdateNewGroupCallMessage creates a new UpdateNewGroupCallMessage
func NewUpdateNewGroupCallMessage(filter filters.UpdateNewGroupCallMessage, response func(b *gotdbot.Client, u *gotdbot.UpdateNewGroupCallMessage) error) *UpdateNewGroupCallMessage {
	return &UpdateNewGroupCallMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewGroupCallMessage) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewGroupCallMessage)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewGroupCallMessage) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewGroupCallMessage))
}
