// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatBlockList A chat was blocked or unblocked
type UpdateChatBlockList struct {
	Filter   filters.UpdateChatBlockList
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatBlockList) error
}

// NewUpdateChatBlockList creates a new UpdateChatBlockList
func NewUpdateChatBlockList(filter filters.UpdateChatBlockList, response func(b *gotdbot.Client, u *gotdbot.UpdateChatBlockList) error) *UpdateChatBlockList {
	return &UpdateChatBlockList{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatBlockList) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatBlockList)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatBlockList) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatBlockList))
}
