// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateUnconfirmedSession The first unconfirmed session has changed
type UpdateUnconfirmedSession struct {
	Filter   filters.UpdateUnconfirmedSession
	Response func(b *gotdbot.Client, u *gotdbot.UpdateUnconfirmedSession) error
}

// NewUpdateUnconfirmedSession creates a new UpdateUnconfirmedSession
func NewUpdateUnconfirmedSession(filter filters.UpdateUnconfirmedSession, response func(b *gotdbot.Client, u *gotdbot.UpdateUnconfirmedSession) error) *UpdateUnconfirmedSession {
	return &UpdateUnconfirmedSession{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUnconfirmedSession) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateUnconfirmedSession)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUnconfirmedSession) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateUnconfirmedSession))
}
