// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAgeVerificationParameters The parameters for age verification of the current user's account has changed
type UpdateAgeVerificationParameters struct {
	Filter   filters.UpdateAgeVerificationParameters
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAgeVerificationParameters) error
}

// NewUpdateAgeVerificationParameters creates a new UpdateAgeVerificationParameters
func NewUpdateAgeVerificationParameters(filter filters.UpdateAgeVerificationParameters, response func(b *gotdbot.Client, u *gotdbot.UpdateAgeVerificationParameters) error) *UpdateAgeVerificationParameters {
	return &UpdateAgeVerificationParameters{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAgeVerificationParameters) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAgeVerificationParameters)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAgeVerificationParameters) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAgeVerificationParameters))
}
