// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateQuickReplyShortcut Basic information about a quick reply shortcut has changed. This update is guaranteed to come before the quick shortcut name is returned to the application
type UpdateQuickReplyShortcut struct {
	Filter   filters.UpdateQuickReplyShortcut
	Response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcut) error
}

// NewUpdateQuickReplyShortcut creates a new UpdateQuickReplyShortcut
func NewUpdateQuickReplyShortcut(filter filters.UpdateQuickReplyShortcut, response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcut) error) *UpdateQuickReplyShortcut {
	return &UpdateQuickReplyShortcut{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateQuickReplyShortcut) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateQuickReplyShortcut)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateQuickReplyShortcut) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateQuickReplyShortcut))
}
