// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFreezeState The freeze state of the current user's account has changed
type UpdateFreezeState struct {
	Filter   filters.UpdateFreezeState
	Response func(b *gotdbot.Client, u *gotdbot.UpdateFreezeState) error
}

// NewUpdateFreezeState creates a new UpdateFreezeState
func NewUpdateFreezeState(filter filters.UpdateFreezeState, response func(b *gotdbot.Client, u *gotdbot.UpdateFreezeState) error) *UpdateFreezeState {
	return &UpdateFreezeState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFreezeState) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateFreezeState)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFreezeState) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateFreezeState))
}
