// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateQuickReplyShortcutMessages The list of quick reply shortcut messages has changed
type UpdateQuickReplyShortcutMessages struct {
	Filter   filters.UpdateQuickReplyShortcutMessages
	Response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcutMessages) error
}

// NewUpdateQuickReplyShortcutMessages creates a new UpdateQuickReplyShortcutMessages
func NewUpdateQuickReplyShortcutMessages(filter filters.UpdateQuickReplyShortcutMessages, response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcutMessages) error) *UpdateQuickReplyShortcutMessages {
	return &UpdateQuickReplyShortcutMessages{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateQuickReplyShortcutMessages) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateQuickReplyShortcutMessages)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateQuickReplyShortcutMessages) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateQuickReplyShortcutMessages))
}
