// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewChatJoinRequest A user sent a join request to a chat; for bots only
type UpdateNewChatJoinRequest struct {
	Filter   filters.UpdateNewChatJoinRequest
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewChatJoinRequest) error
}

// NewUpdateNewChatJoinRequest creates a new UpdateNewChatJoinRequest
func NewUpdateNewChatJoinRequest(filter filters.UpdateNewChatJoinRequest, response func(b *gotdbot.Client, u *gotdbot.UpdateNewChatJoinRequest) error) *UpdateNewChatJoinRequest {
	return &UpdateNewChatJoinRequest{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewChatJoinRequest) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewChatJoinRequest)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewChatJoinRequest) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewChatJoinRequest))
}
