// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGroupCallMessageLevels The levels of live story group call messages have changed
type UpdateGroupCallMessageLevels struct {
	Filter   filters.UpdateGroupCallMessageLevels
	Response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCallMessageLevels) error
}

// NewUpdateGroupCallMessageLevels creates a new UpdateGroupCallMessageLevels
func NewUpdateGroupCallMessageLevels(filter filters.UpdateGroupCallMessageLevels, response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCallMessageLevels) error) *UpdateGroupCallMessageLevels {
	return &UpdateGroupCallMessageLevels{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallMessageLevels) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateGroupCallMessageLevels)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallMessageLevels) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateGroupCallMessageLevels))
}
