// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSuggestedActions The list of suggested to the user actions has changed
type UpdateSuggestedActions struct {
	Filter   filters.UpdateSuggestedActions
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSuggestedActions) error
}

// NewUpdateSuggestedActions creates a new UpdateSuggestedActions
func NewUpdateSuggestedActions(filter filters.UpdateSuggestedActions, response func(b *gotdbot.Client, u *gotdbot.UpdateSuggestedActions) error) *UpdateSuggestedActions {
	return &UpdateSuggestedActions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSuggestedActions) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSuggestedActions)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSuggestedActions) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSuggestedActions))
}
