// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateTopicMessageCount Number of messages in a topic has changed; for Saved Messages and channel direct messages chat topics only
type UpdateTopicMessageCount struct {
	Filter   filters.UpdateTopicMessageCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateTopicMessageCount) error
}

// NewUpdateTopicMessageCount creates a new UpdateTopicMessageCount
func NewUpdateTopicMessageCount(filter filters.UpdateTopicMessageCount, response func(b *gotdbot.Client, u *gotdbot.UpdateTopicMessageCount) error) *UpdateTopicMessageCount {
	return &UpdateTopicMessageCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTopicMessageCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateTopicMessageCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTopicMessageCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateTopicMessageCount))
}
