// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSavedNotificationSounds The list of saved notification sounds was updated. This update may not be sent until information about a notification sound was requested for the first time
type UpdateSavedNotificationSounds struct {
	Filter   filters.UpdateSavedNotificationSounds
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSavedNotificationSounds) error
}

// NewUpdateSavedNotificationSounds creates a new UpdateSavedNotificationSounds
func NewUpdateSavedNotificationSounds(filter filters.UpdateSavedNotificationSounds, response func(b *gotdbot.Client, u *gotdbot.UpdateSavedNotificationSounds) error) *UpdateSavedNotificationSounds {
	return &UpdateSavedNotificationSounds{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedNotificationSounds) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSavedNotificationSounds)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedNotificationSounds) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSavedNotificationSounds))
}
