// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewCallbackQuery A new incoming callback query; for bots only
type UpdateNewCallbackQuery struct {
	Filter   filters.UpdateNewCallbackQuery
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewCallbackQuery) error
}

// NewUpdateNewCallbackQuery creates a new UpdateNewCallbackQuery
func NewUpdateNewCallbackQuery(filter filters.UpdateNewCallbackQuery, response func(b *gotdbot.Client, u *gotdbot.UpdateNewCallbackQuery) error) *UpdateNewCallbackQuery {
	return &UpdateNewCallbackQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewCallbackQuery) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewCallbackQuery)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewCallbackQuery) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewCallbackQuery))
}
