// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateBusinessMessagesDeleted Messages in a business account were deleted; for bots only
type UpdateBusinessMessagesDeleted struct {
	Filter   filters.UpdateBusinessMessagesDeleted
	Response func(b *gotdbot.Client, u *gotdbot.UpdateBusinessMessagesDeleted) error
}

// NewUpdateBusinessMessagesDeleted creates a new UpdateBusinessMessagesDeleted
func NewUpdateBusinessMessagesDeleted(filter filters.UpdateBusinessMessagesDeleted, response func(b *gotdbot.Client, u *gotdbot.UpdateBusinessMessagesDeleted) error) *UpdateBusinessMessagesDeleted {
	return &UpdateBusinessMessagesDeleted{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateBusinessMessagesDeleted) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateBusinessMessagesDeleted)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateBusinessMessagesDeleted) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateBusinessMessagesDeleted))
}
