// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateWebAppMessageSent A message was sent by an opened Web App, so the Web App needs to be closed
type UpdateWebAppMessageSent struct {
	Filter   filters.UpdateWebAppMessageSent
	Response func(b *gotdbot.Client, u *gotdbot.UpdateWebAppMessageSent) error
}

// NewUpdateWebAppMessageSent creates a new UpdateWebAppMessageSent
func NewUpdateWebAppMessageSent(filter filters.UpdateWebAppMessageSent, response func(b *gotdbot.Client, u *gotdbot.UpdateWebAppMessageSent) error) *UpdateWebAppMessageSent {
	return &UpdateWebAppMessageSent{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateWebAppMessageSent) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateWebAppMessageSent)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateWebAppMessageSent) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateWebAppMessageSent))
}
