// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateStickerSet A sticker set has changed
type UpdateStickerSet struct {
	Filter   filters.UpdateStickerSet
	Response func(b *gotdbot.Client, u *gotdbot.UpdateStickerSet) error
}

// NewUpdateStickerSet creates a new UpdateStickerSet
func NewUpdateStickerSet(filter filters.UpdateStickerSet, response func(b *gotdbot.Client, u *gotdbot.UpdateStickerSet) error) *UpdateStickerSet {
	return &UpdateStickerSet{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStickerSet) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateStickerSet)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStickerSet) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateStickerSet))
}
