// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageReaction User changed its reactions on a message with public reactions; for bots only
type UpdateMessageReaction struct {
	Filter   filters.UpdateMessageReaction
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageReaction) error
}

// NewUpdateMessageReaction creates a new UpdateMessageReaction
func NewUpdateMessageReaction(filter filters.UpdateMessageReaction, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageReaction) error) *UpdateMessageReaction {
	return &UpdateMessageReaction{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageReaction) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageReaction)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageReaction) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageReaction))
}
