// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatPhoto A chat photo was changed
type UpdateChatPhoto struct {
	Filter   filters.UpdateChatPhoto
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatPhoto) error
}

// NewUpdateChatPhoto creates a new UpdateChatPhoto
func NewUpdateChatPhoto(filter filters.UpdateChatPhoto, response func(b *gotdbot.Client, u *gotdbot.UpdateChatPhoto) error) *UpdateChatPhoto {
	return &UpdateChatPhoto{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatPhoto) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatPhoto)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatPhoto) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatPhoto))
}
