// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewMessage A new message was received; can also be an outgoing message
type UpdateNewMessage struct {
	Filter   filters.UpdateNewMessage
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewMessage) error
}

// NewUpdateNewMessage creates a new UpdateNewMessage
func NewUpdateNewMessage(filter filters.UpdateNewMessage, response func(b *gotdbot.Client, u *gotdbot.UpdateNewMessage) error) *UpdateNewMessage {
	return &UpdateNewMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewMessage) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewMessage)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewMessage) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewMessage))
}
