// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateOwnedStarCount The number of Telegram Stars owned by the current user has changed
type UpdateOwnedStarCount struct {
	Filter   filters.UpdateOwnedStarCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateOwnedStarCount) error
}

// NewUpdateOwnedStarCount creates a new UpdateOwnedStarCount
func NewUpdateOwnedStarCount(filter filters.UpdateOwnedStarCount, response func(b *gotdbot.Client, u *gotdbot.UpdateOwnedStarCount) error) *UpdateOwnedStarCount {
	return &UpdateOwnedStarCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateOwnedStarCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateOwnedStarCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateOwnedStarCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateOwnedStarCount))
}
