// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateUserStatus The user went online or offline
type UpdateUserStatus struct {
	Filter   filters.UpdateUserStatus
	Response func(b *gotdbot.Client, u *gotdbot.UpdateUserStatus) error
}

// NewUpdateUserStatus creates a new UpdateUserStatus
func NewUpdateUserStatus(filter filters.UpdateUserStatus, response func(b *gotdbot.Client, u *gotdbot.UpdateUserStatus) error) *UpdateUserStatus {
	return &UpdateUserStatus{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUserStatus) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateUserStatus)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUserStatus) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateUserStatus))
}
