// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateUserFullInfo Some data in userFullInfo has been changed
type UpdateUserFullInfo struct {
	Filter   filters.UpdateUserFullInfo
	Response func(b *gotdbot.Client, u *gotdbot.UpdateUserFullInfo) error
}

// NewUpdateUserFullInfo creates a new UpdateUserFullInfo
func NewUpdateUserFullInfo(filter filters.UpdateUserFullInfo, response func(b *gotdbot.Client, u *gotdbot.UpdateUserFullInfo) error) *UpdateUserFullInfo {
	return &UpdateUserFullInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUserFullInfo) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateUserFullInfo)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUserFullInfo) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateUserFullInfo))
}
