// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewOauthRequest An OAuth authorization request was received
type UpdateNewOauthRequest struct {
	Filter   filters.UpdateNewOauthRequest
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewOauthRequest) error
}

// NewUpdateNewOauthRequest creates a new UpdateNewOauthRequest
func NewUpdateNewOauthRequest(filter filters.UpdateNewOauthRequest, response func(b *gotdbot.Client, u *gotdbot.UpdateNewOauthRequest) error) *UpdateNewOauthRequest {
	return &UpdateNewOauthRequest{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewOauthRequest) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewOauthRequest)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewOauthRequest) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewOauthRequest))
}
