// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGiftAuctionState State of a gift auction was updated
type UpdateGiftAuctionState struct {
	Filter   filters.UpdateGiftAuctionState
	Response func(b *gotdbot.Client, u *gotdbot.UpdateGiftAuctionState) error
}

// NewUpdateGiftAuctionState creates a new UpdateGiftAuctionState
func NewUpdateGiftAuctionState(filter filters.UpdateGiftAuctionState, response func(b *gotdbot.Client, u *gotdbot.UpdateGiftAuctionState) error) *UpdateGiftAuctionState {
	return &UpdateGiftAuctionState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGiftAuctionState) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateGiftAuctionState)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGiftAuctionState) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateGiftAuctionState))
}
