// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateActiveGiftAuctions The list of auctions in which participate the current user has changed
type UpdateActiveGiftAuctions struct {
	Filter   filters.UpdateActiveGiftAuctions
	Response func(b *gotdbot.Client, u *gotdbot.UpdateActiveGiftAuctions) error
}

// NewUpdateActiveGiftAuctions creates a new UpdateActiveGiftAuctions
func NewUpdateActiveGiftAuctions(filter filters.UpdateActiveGiftAuctions, response func(b *gotdbot.Client, u *gotdbot.UpdateActiveGiftAuctions) error) *UpdateActiveGiftAuctions {
	return &UpdateActiveGiftAuctions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateActiveGiftAuctions) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateActiveGiftAuctions)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateActiveGiftAuctions) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateActiveGiftAuctions))
}
