// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewCallSignalingData New call signaling data arrived
type UpdateNewCallSignalingData struct {
	Filter   filters.UpdateNewCallSignalingData
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewCallSignalingData) error
}

// NewUpdateNewCallSignalingData creates a new UpdateNewCallSignalingData
func NewUpdateNewCallSignalingData(filter filters.UpdateNewCallSignalingData, response func(b *gotdbot.Client, u *gotdbot.UpdateNewCallSignalingData) error) *UpdateNewCallSignalingData {
	return &UpdateNewCallSignalingData{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewCallSignalingData) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewCallSignalingData)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewCallSignalingData) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewCallSignalingData))
}
