// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateRecentStickers The list of recently used stickers was updated
type UpdateRecentStickers struct {
	Filter   filters.UpdateRecentStickers
	Response func(b *gotdbot.Client, u *gotdbot.UpdateRecentStickers) error
}

// NewUpdateRecentStickers creates a new UpdateRecentStickers
func NewUpdateRecentStickers(filter filters.UpdateRecentStickers, response func(b *gotdbot.Client, u *gotdbot.UpdateRecentStickers) error) *UpdateRecentStickers {
	return &UpdateRecentStickers{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateRecentStickers) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateRecentStickers)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateRecentStickers) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateRecentStickers))
}
