// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageSendFailed A message failed to send. Be aware that some messages being sent can be irrecoverably deleted, in which case updateDeleteMessages will be received instead of this update
type UpdateMessageSendFailed struct {
	Filter   filters.UpdateMessageSendFailed
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSendFailed) error
}

// NewUpdateMessageSendFailed creates a new UpdateMessageSendFailed
func NewUpdateMessageSendFailed(filter filters.UpdateMessageSendFailed, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSendFailed) error) *UpdateMessageSendFailed {
	return &UpdateMessageSendFailed{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSendFailed) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageSendFailed)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSendFailed) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageSendFailed))
}
