// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageContainsUnreadPollVotes Unread votes were added or removed from a poll message
type UpdateMessageContainsUnreadPollVotes struct {
	Filter   filters.UpdateMessageContainsUnreadPollVotes
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageContainsUnreadPollVotes) error
}

// NewUpdateMessageContainsUnreadPollVotes creates a new UpdateMessageContainsUnreadPollVotes
func NewUpdateMessageContainsUnreadPollVotes(filter filters.UpdateMessageContainsUnreadPollVotes, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageContainsUnreadPollVotes) error) *UpdateMessageContainsUnreadPollVotes {
	return &UpdateMessageContainsUnreadPollVotes{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageContainsUnreadPollVotes) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageContainsUnreadPollVotes)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageContainsUnreadPollVotes) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageContainsUnreadPollVotes))
}
