// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageContentOpened The message content was opened. Updates voice note messages to "listened", video note messages to "viewed" and starts the self-destruct timer
type UpdateMessageContentOpened struct {
	Filter   filters.UpdateMessageContentOpened
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageContentOpened) error
}

// NewUpdateMessageContentOpened creates a new UpdateMessageContentOpened
func NewUpdateMessageContentOpened(filter filters.UpdateMessageContentOpened, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageContentOpened) error) *UpdateMessageContentOpened {
	return &UpdateMessageContentOpened{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageContentOpened) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageContentOpened)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageContentOpened) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageContentOpened))
}
