// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewGroupCallPaidReaction A new paid reaction was received in a live story group call
type UpdateNewGroupCallPaidReaction struct {
	Filter   filters.UpdateNewGroupCallPaidReaction
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewGroupCallPaidReaction) error
}

// NewUpdateNewGroupCallPaidReaction creates a new UpdateNewGroupCallPaidReaction
func NewUpdateNewGroupCallPaidReaction(filter filters.UpdateNewGroupCallPaidReaction, response func(b *gotdbot.Client, u *gotdbot.UpdateNewGroupCallPaidReaction) error) *UpdateNewGroupCallPaidReaction {
	return &UpdateNewGroupCallPaidReaction{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewGroupCallPaidReaction) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewGroupCallPaidReaction)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewGroupCallPaidReaction) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewGroupCallPaidReaction))
}
