// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatVideoChat A chat video chat state has changed
type UpdateChatVideoChat struct {
	Filter   filters.UpdateChatVideoChat
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatVideoChat) error
}

// NewUpdateChatVideoChat creates a new UpdateChatVideoChat
func NewUpdateChatVideoChat(filter filters.UpdateChatVideoChat, response func(b *gotdbot.Client, u *gotdbot.UpdateChatVideoChat) error) *UpdateChatVideoChat {
	return &UpdateChatVideoChat{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatVideoChat) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatVideoChat)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatVideoChat) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatVideoChat))
}
