// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateDeleteMessages Some messages were deleted
type UpdateDeleteMessages struct {
	Filter   filters.UpdateDeleteMessages
	Response func(b *gotdbot.Client, u *gotdbot.UpdateDeleteMessages) error
}

// NewUpdateDeleteMessages creates a new UpdateDeleteMessages
func NewUpdateDeleteMessages(filter filters.UpdateDeleteMessages, response func(b *gotdbot.Client, u *gotdbot.UpdateDeleteMessages) error) *UpdateDeleteMessages {
	return &UpdateDeleteMessages{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateDeleteMessages) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateDeleteMessages)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateDeleteMessages) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateDeleteMessages))
}
