// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNotificationGroup A list of active notifications in a notification group has changed
type UpdateNotificationGroup struct {
	Filter   filters.UpdateNotificationGroup
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNotificationGroup) error
}

// NewUpdateNotificationGroup creates a new UpdateNotificationGroup
func NewUpdateNotificationGroup(filter filters.UpdateNotificationGroup, response func(b *gotdbot.Client, u *gotdbot.UpdateNotificationGroup) error) *UpdateNotificationGroup {
	return &UpdateNotificationGroup{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNotificationGroup) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNotificationGroup)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNotificationGroup) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNotificationGroup))
}
