// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateForumTopic Information about a topic in a forum chat was changed
type UpdateForumTopic struct {
	Filter   filters.UpdateForumTopic
	Response func(b *gotdbot.Client, u *gotdbot.UpdateForumTopic) error
}

// NewUpdateForumTopic creates a new UpdateForumTopic
func NewUpdateForumTopic(filter filters.UpdateForumTopic, response func(b *gotdbot.Client, u *gotdbot.UpdateForumTopic) error) *UpdateForumTopic {
	return &UpdateForumTopic{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateForumTopic) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateForumTopic)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateForumTopic) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateForumTopic))
}
