// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSavedMessagesTopicCount Number of Saved Messages topics has changed
type UpdateSavedMessagesTopicCount struct {
	Filter   filters.UpdateSavedMessagesTopicCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSavedMessagesTopicCount) error
}

// NewUpdateSavedMessagesTopicCount creates a new UpdateSavedMessagesTopicCount
func NewUpdateSavedMessagesTopicCount(filter filters.UpdateSavedMessagesTopicCount, response func(b *gotdbot.Client, u *gotdbot.UpdateSavedMessagesTopicCount) error) *UpdateSavedMessagesTopicCount {
	return &UpdateSavedMessagesTopicCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedMessagesTopicCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSavedMessagesTopicCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedMessagesTopicCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSavedMessagesTopicCount))
}
