// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewBusinessCallbackQuery A new incoming callback query from a business message; for bots only
type UpdateNewBusinessCallbackQuery struct {
	Filter   filters.UpdateNewBusinessCallbackQuery
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewBusinessCallbackQuery) error
}

// NewUpdateNewBusinessCallbackQuery creates a new UpdateNewBusinessCallbackQuery
func NewUpdateNewBusinessCallbackQuery(filter filters.UpdateNewBusinessCallbackQuery, response func(b *gotdbot.Client, u *gotdbot.UpdateNewBusinessCallbackQuery) error) *UpdateNewBusinessCallbackQuery {
	return &UpdateNewBusinessCallbackQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewBusinessCallbackQuery) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewBusinessCallbackQuery)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewBusinessCallbackQuery) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewBusinessCallbackQuery))
}
