// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGroupCall Information about a group call was updated
type UpdateGroupCall struct {
	Filter   filters.UpdateGroupCall
	Response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCall) error
}

// NewUpdateGroupCall creates a new UpdateGroupCall
func NewUpdateGroupCall(filter filters.UpdateGroupCall, response func(b *gotdbot.Client, u *gotdbot.UpdateGroupCall) error) *UpdateGroupCall {
	return &UpdateGroupCall{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCall) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateGroupCall)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCall) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateGroupCall))
}
