// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageMentionRead A message with an unread mention was read
type UpdateMessageMentionRead struct {
	Filter   filters.UpdateMessageMentionRead
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageMentionRead) error
}

// NewUpdateMessageMentionRead creates a new UpdateMessageMentionRead
func NewUpdateMessageMentionRead(filter filters.UpdateMessageMentionRead, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageMentionRead) error) *UpdateMessageMentionRead {
	return &UpdateMessageMentionRead{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageMentionRead) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageMentionRead)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageMentionRead) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageMentionRead))
}
