// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatPermissions Chat permissions were changed
type UpdateChatPermissions struct {
	Filter   filters.UpdateChatPermissions
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatPermissions) error
}

// NewUpdateChatPermissions creates a new UpdateChatPermissions
func NewUpdateChatPermissions(filter filters.UpdateChatPermissions, response func(b *gotdbot.Client, u *gotdbot.UpdateChatPermissions) error) *UpdateChatPermissions {
	return &UpdateChatPermissions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatPermissions) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatPermissions)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatPermissions) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatPermissions))
}
