// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateDiceEmojis The list of supported dice emojis has changed
type UpdateDiceEmojis struct {
	Filter   filters.UpdateDiceEmojis
	Response func(b *gotdbot.Client, u *gotdbot.UpdateDiceEmojis) error
}

// NewUpdateDiceEmojis creates a new UpdateDiceEmojis
func NewUpdateDiceEmojis(filter filters.UpdateDiceEmojis, response func(b *gotdbot.Client, u *gotdbot.UpdateDiceEmojis) error) *UpdateDiceEmojis {
	return &UpdateDiceEmojis{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateDiceEmojis) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateDiceEmojis)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateDiceEmojis) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateDiceEmojis))
}
