// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateProfileAccentColors The list of supported accent colors for user profiles has changed
type UpdateProfileAccentColors struct {
	Filter   filters.UpdateProfileAccentColors
	Response func(b *gotdbot.Client, u *gotdbot.UpdateProfileAccentColors) error
}

// NewUpdateProfileAccentColors creates a new UpdateProfileAccentColors
func NewUpdateProfileAccentColors(filter filters.UpdateProfileAccentColors, response func(b *gotdbot.Client, u *gotdbot.UpdateProfileAccentColors) error) *UpdateProfileAccentColors {
	return &UpdateProfileAccentColors{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateProfileAccentColors) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateProfileAccentColors)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateProfileAccentColors) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateProfileAccentColors))
}
