// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageContent The message content has changed
type UpdateMessageContent struct {
	Filter   filters.UpdateMessageContent
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageContent) error
}

// NewUpdateMessageContent creates a new UpdateMessageContent
func NewUpdateMessageContent(filter filters.UpdateMessageContent, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageContent) error) *UpdateMessageContent {
	return &UpdateMessageContent{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageContent) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageContent)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageContent) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageContent))
}
