// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatRevenueAmount The revenue earned from sponsored messages in a chat has changed. If chat revenue screen is opened, then getChatRevenueTransactions may be called to fetch new transactions
type UpdateChatRevenueAmount struct {
	Filter   filters.UpdateChatRevenueAmount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatRevenueAmount) error
}

// NewUpdateChatRevenueAmount creates a new UpdateChatRevenueAmount
func NewUpdateChatRevenueAmount(filter filters.UpdateChatRevenueAmount, response func(b *gotdbot.Client, u *gotdbot.UpdateChatRevenueAmount) error) *UpdateChatRevenueAmount {
	return &UpdateChatRevenueAmount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatRevenueAmount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatRevenueAmount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatRevenueAmount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatRevenueAmount))
}
