// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFavoriteStickers The list of favorite stickers was updated
type UpdateFavoriteStickers struct {
	Filter   filters.UpdateFavoriteStickers
	Response func(b *gotdbot.Client, u *gotdbot.UpdateFavoriteStickers) error
}

// NewUpdateFavoriteStickers creates a new UpdateFavoriteStickers
func NewUpdateFavoriteStickers(filter filters.UpdateFavoriteStickers, response func(b *gotdbot.Client, u *gotdbot.UpdateFavoriteStickers) error) *UpdateFavoriteStickers {
	return &UpdateFavoriteStickers{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFavoriteStickers) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateFavoriteStickers)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFavoriteStickers) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateFavoriteStickers))
}
