// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatNotificationSettings Notification settings for a chat were changed
type UpdateChatNotificationSettings struct {
	Filter   filters.UpdateChatNotificationSettings
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatNotificationSettings) error
}

// NewUpdateChatNotificationSettings creates a new UpdateChatNotificationSettings
func NewUpdateChatNotificationSettings(filter filters.UpdateChatNotificationSettings, response func(b *gotdbot.Client, u *gotdbot.UpdateChatNotificationSettings) error) *UpdateChatNotificationSettings {
	return &UpdateChatNotificationSettings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatNotificationSettings) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatNotificationSettings)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatNotificationSettings) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatNotificationSettings))
}
