// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatHasProtectedContent A chat content was allowed or restricted for saving
type UpdateChatHasProtectedContent struct {
	Filter   filters.UpdateChatHasProtectedContent
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatHasProtectedContent) error
}

// NewUpdateChatHasProtectedContent creates a new UpdateChatHasProtectedContent
func NewUpdateChatHasProtectedContent(filter filters.UpdateChatHasProtectedContent, response func(b *gotdbot.Client, u *gotdbot.UpdateChatHasProtectedContent) error) *UpdateChatHasProtectedContent {
	return &UpdateChatHasProtectedContent{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatHasProtectedContent) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatHasProtectedContent)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatHasProtectedContent) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatHasProtectedContent))
}
