// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateActiveLiveLocationMessages The list of messages with active live location that need to be updated by the application has changed. The list is persistent across application restarts only if the message database is used
type UpdateActiveLiveLocationMessages struct {
	Filter   filters.UpdateActiveLiveLocationMessages
	Response func(b *gotdbot.Client, u *gotdbot.UpdateActiveLiveLocationMessages) error
}

// NewUpdateActiveLiveLocationMessages creates a new UpdateActiveLiveLocationMessages
func NewUpdateActiveLiveLocationMessages(filter filters.UpdateActiveLiveLocationMessages, response func(b *gotdbot.Client, u *gotdbot.UpdateActiveLiveLocationMessages) error) *UpdateActiveLiveLocationMessages {
	return &UpdateActiveLiveLocationMessages{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateActiveLiveLocationMessages) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateActiveLiveLocationMessages)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateActiveLiveLocationMessages) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateActiveLiveLocationMessages))
}
