// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageSendSucceeded A message has been successfully sent
type UpdateMessageSendSucceeded struct {
	Filter   filters.UpdateMessageSendSucceeded
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSendSucceeded) error
}

// NewUpdateMessageSendSucceeded creates a new UpdateMessageSendSucceeded
func NewUpdateMessageSendSucceeded(filter filters.UpdateMessageSendSucceeded, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageSendSucceeded) error) *UpdateMessageSendSucceeded {
	return &UpdateMessageSendSucceeded{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSendSucceeded) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageSendSucceeded)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSendSucceeded) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageSendSucceeded))
}
