// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatReadOutbox Outgoing messages were read
type UpdateChatReadOutbox struct {
	Filter   filters.UpdateChatReadOutbox
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatReadOutbox) error
}

// NewUpdateChatReadOutbox creates a new UpdateChatReadOutbox
func NewUpdateChatReadOutbox(filter filters.UpdateChatReadOutbox, response func(b *gotdbot.Client, u *gotdbot.UpdateChatReadOutbox) error) *UpdateChatReadOutbox {
	return &UpdateChatReadOutbox{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatReadOutbox) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatReadOutbox)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatReadOutbox) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatReadOutbox))
}
