// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatUnreadMentionCount The chat unread_mention_count has changed
type UpdateChatUnreadMentionCount struct {
	Filter   filters.UpdateChatUnreadMentionCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatUnreadMentionCount) error
}

// NewUpdateChatUnreadMentionCount creates a new UpdateChatUnreadMentionCount
func NewUpdateChatUnreadMentionCount(filter filters.UpdateChatUnreadMentionCount, response func(b *gotdbot.Client, u *gotdbot.UpdateChatUnreadMentionCount) error) *UpdateChatUnreadMentionCount {
	return &UpdateChatUnreadMentionCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatUnreadMentionCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatUnreadMentionCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatUnreadMentionCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatUnreadMentionCount))
}
