// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdatePoll A poll was updated; for bots only
type UpdatePoll struct {
	Filter   filters.UpdatePoll
	Response func(b *gotdbot.Client, u *gotdbot.UpdatePoll) error
}

// NewUpdatePoll creates a new UpdatePoll
func NewUpdatePoll(filter filters.UpdatePoll, response func(b *gotdbot.Client, u *gotdbot.UpdatePoll) error) *UpdatePoll {
	return &UpdatePoll{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdatePoll) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdatePoll)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdatePoll) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdatePoll))
}
