// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSavedMessagesTags Tags used in Saved Messages or a Saved Messages topic have changed
type UpdateSavedMessagesTags struct {
	Filter   filters.UpdateSavedMessagesTags
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSavedMessagesTags) error
}

// NewUpdateSavedMessagesTags creates a new UpdateSavedMessagesTags
func NewUpdateSavedMessagesTags(filter filters.UpdateSavedMessagesTags, response func(b *gotdbot.Client, u *gotdbot.UpdateSavedMessagesTags) error) *UpdateSavedMessagesTags {
	return &UpdateSavedMessagesTags{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedMessagesTags) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSavedMessagesTags)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedMessagesTags) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSavedMessagesTags))
}
