// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAuthorizationState The user authorization state has changed
type UpdateAuthorizationState struct {
	Filter   filters.UpdateAuthorizationState
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAuthorizationState) error
}

// NewUpdateAuthorizationState creates a new UpdateAuthorizationState
func NewUpdateAuthorizationState(filter filters.UpdateAuthorizationState, response func(b *gotdbot.Client, u *gotdbot.UpdateAuthorizationState) error) *UpdateAuthorizationState {
	return &UpdateAuthorizationState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAuthorizationState) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAuthorizationState)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAuthorizationState) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAuthorizationState))
}
