// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSupergroup Some data of a supergroup or a channel has changed. This update is guaranteed to come before the supergroup identifier is returned to the application
type UpdateSupergroup struct {
	Filter   filters.UpdateSupergroup
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSupergroup) error
}

// NewUpdateSupergroup creates a new UpdateSupergroup
func NewUpdateSupergroup(filter filters.UpdateSupergroup, response func(b *gotdbot.Client, u *gotdbot.UpdateSupergroup) error) *UpdateSupergroup {
	return &UpdateSupergroup{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSupergroup) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSupergroup)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSupergroup) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSupergroup))
}
