// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateScopeNotificationSettings Notification settings for some type of chats were updated
type UpdateScopeNotificationSettings struct {
	Filter   filters.UpdateScopeNotificationSettings
	Response func(b *gotdbot.Client, u *gotdbot.UpdateScopeNotificationSettings) error
}

// NewUpdateScopeNotificationSettings creates a new UpdateScopeNotificationSettings
func NewUpdateScopeNotificationSettings(filter filters.UpdateScopeNotificationSettings, response func(b *gotdbot.Client, u *gotdbot.UpdateScopeNotificationSettings) error) *UpdateScopeNotificationSettings {
	return &UpdateScopeNotificationSettings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateScopeNotificationSettings) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateScopeNotificationSettings)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateScopeNotificationSettings) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateScopeNotificationSettings))
}
