// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFileGenerationStart The file generation process needs to be started by the application. Use setFileGenerationProgress and finishFileGeneration to generate the file
type UpdateFileGenerationStart struct {
	Filter   filters.UpdateFileGenerationStart
	Response func(b *gotdbot.Client, u *gotdbot.UpdateFileGenerationStart) error
}

// NewUpdateFileGenerationStart creates a new UpdateFileGenerationStart
func NewUpdateFileGenerationStart(filter filters.UpdateFileGenerationStart, response func(b *gotdbot.Client, u *gotdbot.UpdateFileGenerationStart) error) *UpdateFileGenerationStart {
	return &UpdateFileGenerationStart{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFileGenerationStart) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateFileGenerationStart)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFileGenerationStart) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateFileGenerationStart))
}
