// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatMessageAutoDeleteTime The message auto-delete or self-destruct timer setting for a chat was changed
type UpdateChatMessageAutoDeleteTime struct {
	Filter   filters.UpdateChatMessageAutoDeleteTime
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatMessageAutoDeleteTime) error
}

// NewUpdateChatMessageAutoDeleteTime creates a new UpdateChatMessageAutoDeleteTime
func NewUpdateChatMessageAutoDeleteTime(filter filters.UpdateChatMessageAutoDeleteTime, response func(b *gotdbot.Client, u *gotdbot.UpdateChatMessageAutoDeleteTime) error) *UpdateChatMessageAutoDeleteTime {
	return &UpdateChatMessageAutoDeleteTime{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatMessageAutoDeleteTime) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatMessageAutoDeleteTime)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatMessageAutoDeleteTime) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatMessageAutoDeleteTime))
}
