// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAccentColors The list of supported accent colors has changed
type UpdateAccentColors struct {
	Filter   filters.UpdateAccentColors
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAccentColors) error
}

// NewUpdateAccentColors creates a new UpdateAccentColors
func NewUpdateAccentColors(filter filters.UpdateAccentColors, response func(b *gotdbot.Client, u *gotdbot.UpdateAccentColors) error) *UpdateAccentColors {
	return &UpdateAccentColors{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAccentColors) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAccentColors)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAccentColors) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAccentColors))
}
