// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageLiveLocationViewed A message with a live location was viewed. When the update is received, the application is expected to update the live location
type UpdateMessageLiveLocationViewed struct {
	Filter   filters.UpdateMessageLiveLocationViewed
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageLiveLocationViewed) error
}

// NewUpdateMessageLiveLocationViewed creates a new UpdateMessageLiveLocationViewed
func NewUpdateMessageLiveLocationViewed(filter filters.UpdateMessageLiveLocationViewed, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageLiveLocationViewed) error) *UpdateMessageLiveLocationViewed {
	return &UpdateMessageLiveLocationViewed{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageLiveLocationViewed) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageLiveLocationViewed)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageLiveLocationViewed) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageLiveLocationViewed))
}
