// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatMessageSender The message sender that is selected to send messages in a chat has changed
type UpdateChatMessageSender struct {
	Filter   filters.UpdateChatMessageSender
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatMessageSender) error
}

// NewUpdateChatMessageSender creates a new UpdateChatMessageSender
func NewUpdateChatMessageSender(filter filters.UpdateChatMessageSender, response func(b *gotdbot.Client, u *gotdbot.UpdateChatMessageSender) error) *UpdateChatMessageSender {
	return &UpdateChatMessageSender{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatMessageSender) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatMessageSender)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatMessageSender) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatMessageSender))
}
