// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSavedAnimations The list of saved animations was updated
type UpdateSavedAnimations struct {
	Filter   filters.UpdateSavedAnimations
	Response func(b *gotdbot.Client, u *gotdbot.UpdateSavedAnimations) error
}

// NewUpdateSavedAnimations creates a new UpdateSavedAnimations
func NewUpdateSavedAnimations(filter filters.UpdateSavedAnimations, response func(b *gotdbot.Client, u *gotdbot.UpdateSavedAnimations) error) *UpdateSavedAnimations {
	return &UpdateSavedAnimations{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedAnimations) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateSavedAnimations)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedAnimations) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateSavedAnimations))
}
