// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatTitle The title of a chat was changed
type UpdateChatTitle struct {
	Filter   filters.UpdateChatTitle
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatTitle) error
}

// NewUpdateChatTitle creates a new UpdateChatTitle
func NewUpdateChatTitle(filter filters.UpdateChatTitle, response func(b *gotdbot.Client, u *gotdbot.UpdateChatTitle) error) *UpdateChatTitle {
	return &UpdateChatTitle{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatTitle) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatTitle)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatTitle) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatTitle))
}
