// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFileGenerationStop File generation is no longer needed
type UpdateFileGenerationStop struct {
	Filter   filters.UpdateFileGenerationStop
	Response func(b *gotdbot.Client, u *gotdbot.UpdateFileGenerationStop) error
}

// NewUpdateFileGenerationStop creates a new UpdateFileGenerationStop
func NewUpdateFileGenerationStop(filter filters.UpdateFileGenerationStop, response func(b *gotdbot.Client, u *gotdbot.UpdateFileGenerationStop) error) *UpdateFileGenerationStop {
	return &UpdateFileGenerationStop{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFileGenerationStop) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateFileGenerationStop)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFileGenerationStop) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateFileGenerationStop))
}
