// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateQuickReplyShortcutDeleted A quick reply shortcut and all its messages were deleted
type UpdateQuickReplyShortcutDeleted struct {
	Filter   filters.UpdateQuickReplyShortcutDeleted
	Response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcutDeleted) error
}

// NewUpdateQuickReplyShortcutDeleted creates a new UpdateQuickReplyShortcutDeleted
func NewUpdateQuickReplyShortcutDeleted(filter filters.UpdateQuickReplyShortcutDeleted, response func(b *gotdbot.Client, u *gotdbot.UpdateQuickReplyShortcutDeleted) error) *UpdateQuickReplyShortcutDeleted {
	return &UpdateQuickReplyShortcutDeleted{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateQuickReplyShortcutDeleted) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateQuickReplyShortcutDeleted)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateQuickReplyShortcutDeleted) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateQuickReplyShortcutDeleted))
}
