// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFileAddedToDownloads A file was added to the file download list. This update is sent only after file download list is loaded for the first time
type UpdateFileAddedToDownloads struct {
	Filter   filters.UpdateFileAddedToDownloads
	Response func(b *gotdbot.Client, u *gotdbot.UpdateFileAddedToDownloads) error
}

// NewUpdateFileAddedToDownloads creates a new UpdateFileAddedToDownloads
func NewUpdateFileAddedToDownloads(filter filters.UpdateFileAddedToDownloads, response func(b *gotdbot.Client, u *gotdbot.UpdateFileAddedToDownloads) error) *UpdateFileAddedToDownloads {
	return &UpdateFileAddedToDownloads{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFileAddedToDownloads) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateFileAddedToDownloads)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFileAddedToDownloads) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateFileAddedToDownloads))
}
