// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateStakeDiceState The stake dice state has changed
type UpdateStakeDiceState struct {
	Filter   filters.UpdateStakeDiceState
	Response func(b *gotdbot.Client, u *gotdbot.UpdateStakeDiceState) error
}

// NewUpdateStakeDiceState creates a new UpdateStakeDiceState
func NewUpdateStakeDiceState(filter filters.UpdateStakeDiceState, response func(b *gotdbot.Client, u *gotdbot.UpdateStakeDiceState) error) *UpdateStakeDiceState {
	return &UpdateStakeDiceState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStakeDiceState) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateStakeDiceState)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStakeDiceState) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateStakeDiceState))
}
