// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateInstalledStickerSets The list of installed sticker sets was updated
type UpdateInstalledStickerSets struct {
	Filter   filters.UpdateInstalledStickerSets
	Response func(b *gotdbot.Client, u *gotdbot.UpdateInstalledStickerSets) error
}

// NewUpdateInstalledStickerSets creates a new UpdateInstalledStickerSets
func NewUpdateInstalledStickerSets(filter filters.UpdateInstalledStickerSets, response func(b *gotdbot.Client, u *gotdbot.UpdateInstalledStickerSets) error) *UpdateInstalledStickerSets {
	return &UpdateInstalledStickerSets{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateInstalledStickerSets) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateInstalledStickerSets)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateInstalledStickerSets) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateInstalledStickerSets))
}
