// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageInteractionInfo The information about interactions with a message has changed
type UpdateMessageInteractionInfo struct {
	Filter   filters.UpdateMessageInteractionInfo
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageInteractionInfo) error
}

// NewUpdateMessageInteractionInfo creates a new UpdateMessageInteractionInfo
func NewUpdateMessageInteractionInfo(filter filters.UpdateMessageInteractionInfo, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageInteractionInfo) error) *UpdateMessageInteractionInfo {
	return &UpdateMessageInteractionInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageInteractionInfo) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageInteractionInfo)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageInteractionInfo) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageInteractionInfo))
}
