// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateContactCloseBirthdays The list of contacts that had birthdays recently or will have birthday soon has changed
type UpdateContactCloseBirthdays struct {
	Filter   filters.UpdateContactCloseBirthdays
	Response func(b *gotdbot.Client, u *gotdbot.UpdateContactCloseBirthdays) error
}

// NewUpdateContactCloseBirthdays creates a new UpdateContactCloseBirthdays
func NewUpdateContactCloseBirthdays(filter filters.UpdateContactCloseBirthdays, response func(b *gotdbot.Client, u *gotdbot.UpdateContactCloseBirthdays) error) *UpdateContactCloseBirthdays {
	return &UpdateContactCloseBirthdays{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateContactCloseBirthdays) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateContactCloseBirthdays)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateContactCloseBirthdays) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateContactCloseBirthdays))
}
