// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatMember User rights changed in a chat; for bots only
type UpdateChatMember struct {
	Filter   filters.UpdateChatMember
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatMember) error
}

// NewUpdateChatMember creates a new UpdateChatMember
func NewUpdateChatMember(filter filters.UpdateChatMember, response func(b *gotdbot.Client, u *gotdbot.UpdateChatMember) error) *UpdateChatMember {
	return &UpdateChatMember{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatMember) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatMember)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatMember) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatMember))
}
