// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateReactionNotificationSettings Notification settings for reactions were updated
type UpdateReactionNotificationSettings struct {
	Filter   filters.UpdateReactionNotificationSettings
	Response func(b *gotdbot.Client, u *gotdbot.UpdateReactionNotificationSettings) error
}

// NewUpdateReactionNotificationSettings creates a new UpdateReactionNotificationSettings
func NewUpdateReactionNotificationSettings(filter filters.UpdateReactionNotificationSettings, response func(b *gotdbot.Client, u *gotdbot.UpdateReactionNotificationSettings) error) *UpdateReactionNotificationSettings {
	return &UpdateReactionNotificationSettings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateReactionNotificationSettings) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateReactionNotificationSettings)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateReactionNotificationSettings) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateReactionNotificationSettings))
}
