// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageEdited A message was edited. Changes in the message content will come in a separate updateMessageContent
type UpdateMessageEdited struct {
	Filter   filters.UpdateMessageEdited
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageEdited) error
}

// NewUpdateMessageEdited creates a new UpdateMessageEdited
func NewUpdateMessageEdited(filter filters.UpdateMessageEdited, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageEdited) error) *UpdateMessageEdited {
	return &UpdateMessageEdited{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageEdited) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageEdited)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageEdited) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageEdited))
}
