// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNotification A notification was changed
type UpdateNotification struct {
	Filter   filters.UpdateNotification
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNotification) error
}

// NewUpdateNotification creates a new UpdateNotification
func NewUpdateNotification(filter filters.UpdateNotification, response func(b *gotdbot.Client, u *gotdbot.UpdateNotification) error) *UpdateNotification {
	return &UpdateNotification{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNotification) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNotification)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNotification) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNotification))
}
