// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAutosaveSettings Autosave settings for some type of chats were updated
type UpdateAutosaveSettings struct {
	Filter   filters.UpdateAutosaveSettings
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAutosaveSettings) error
}

// NewUpdateAutosaveSettings creates a new UpdateAutosaveSettings
func NewUpdateAutosaveSettings(filter filters.UpdateAutosaveSettings, response func(b *gotdbot.Client, u *gotdbot.UpdateAutosaveSettings) error) *UpdateAutosaveSettings {
	return &UpdateAutosaveSettings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAutosaveSettings) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAutosaveSettings)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAutosaveSettings) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAutosaveSettings))
}
