// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateAnimatedEmojiMessageClicked Some animated emoji message was clicked and a big animated sticker must be played if the message is visible on the screen. chatActionWatchingAnimations with the text of the message needs to be sent if the sticker is played
type UpdateAnimatedEmojiMessageClicked struct {
	Filter   filters.UpdateAnimatedEmojiMessageClicked
	Response func(b *gotdbot.Client, u *gotdbot.UpdateAnimatedEmojiMessageClicked) error
}

// NewUpdateAnimatedEmojiMessageClicked creates a new UpdateAnimatedEmojiMessageClicked
func NewUpdateAnimatedEmojiMessageClicked(filter filters.UpdateAnimatedEmojiMessageClicked, response func(b *gotdbot.Client, u *gotdbot.UpdateAnimatedEmojiMessageClicked) error) *UpdateAnimatedEmojiMessageClicked {
	return &UpdateAnimatedEmojiMessageClicked{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAnimatedEmojiMessageClicked) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateAnimatedEmojiMessageClicked)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAnimatedEmojiMessageClicked) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateAnimatedEmojiMessageClicked))
}
