// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewInlineQuery A new incoming inline query; for bots only
type UpdateNewInlineQuery struct {
	Filter   filters.UpdateNewInlineQuery
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewInlineQuery) error
}

// NewUpdateNewInlineQuery creates a new UpdateNewInlineQuery
func NewUpdateNewInlineQuery(filter filters.UpdateNewInlineQuery, response func(b *gotdbot.Client, u *gotdbot.UpdateNewInlineQuery) error) *UpdateNewInlineQuery {
	return &UpdateNewInlineQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewInlineQuery) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewInlineQuery)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewInlineQuery) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewInlineQuery))
}
