// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatPendingJoinRequests The chat pending join requests were changed
type UpdateChatPendingJoinRequests struct {
	Filter   filters.UpdateChatPendingJoinRequests
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatPendingJoinRequests) error
}

// NewUpdateChatPendingJoinRequests creates a new UpdateChatPendingJoinRequests
func NewUpdateChatPendingJoinRequests(filter filters.UpdateChatPendingJoinRequests, response func(b *gotdbot.Client, u *gotdbot.UpdateChatPendingJoinRequests) error) *UpdateChatPendingJoinRequests {
	return &UpdateChatPendingJoinRequests{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatPendingJoinRequests) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatPendingJoinRequests)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatPendingJoinRequests) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatPendingJoinRequests))
}
