// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateVideoPublished An automatically scheduled message with video has been successfully sent after conversion
type UpdateVideoPublished struct {
	Filter   filters.UpdateVideoPublished
	Response func(b *gotdbot.Client, u *gotdbot.UpdateVideoPublished) error
}

// NewUpdateVideoPublished creates a new UpdateVideoPublished
func NewUpdateVideoPublished(filter filters.UpdateVideoPublished, response func(b *gotdbot.Client, u *gotdbot.UpdateVideoPublished) error) *UpdateVideoPublished {
	return &UpdateVideoPublished{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateVideoPublished) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateVideoPublished)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateVideoPublished) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateVideoPublished))
}
