// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatBusinessBotManageBar The bar for managing business bot was changed in a chat
type UpdateChatBusinessBotManageBar struct {
	Filter   filters.UpdateChatBusinessBotManageBar
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatBusinessBotManageBar) error
}

// NewUpdateChatBusinessBotManageBar creates a new UpdateChatBusinessBotManageBar
func NewUpdateChatBusinessBotManageBar(filter filters.UpdateChatBusinessBotManageBar, response func(b *gotdbot.Client, u *gotdbot.UpdateChatBusinessBotManageBar) error) *UpdateChatBusinessBotManageBar {
	return &UpdateChatBusinessBotManageBar{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatBusinessBotManageBar) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatBusinessBotManageBar)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatBusinessBotManageBar) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatBusinessBotManageBar))
}
