// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateActiveEmojiReactions The list of active emoji reactions has changed
type UpdateActiveEmojiReactions struct {
	Filter   filters.UpdateActiveEmojiReactions
	Response func(b *gotdbot.Client, u *gotdbot.UpdateActiveEmojiReactions) error
}

// NewUpdateActiveEmojiReactions creates a new UpdateActiveEmojiReactions
func NewUpdateActiveEmojiReactions(filter filters.UpdateActiveEmojiReactions, response func(b *gotdbot.Client, u *gotdbot.UpdateActiveEmojiReactions) error) *UpdateActiveEmojiReactions {
	return &UpdateActiveEmojiReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateActiveEmojiReactions) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateActiveEmojiReactions)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateActiveEmojiReactions) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateActiveEmojiReactions))
}
