// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateTrendingStickerSets The list of trending sticker sets was updated or some of them were viewed
type UpdateTrendingStickerSets struct {
	Filter   filters.UpdateTrendingStickerSets
	Response func(b *gotdbot.Client, u *gotdbot.UpdateTrendingStickerSets) error
}

// NewUpdateTrendingStickerSets creates a new UpdateTrendingStickerSets
func NewUpdateTrendingStickerSets(filter filters.UpdateTrendingStickerSets, response func(b *gotdbot.Client, u *gotdbot.UpdateTrendingStickerSets) error) *UpdateTrendingStickerSets {
	return &UpdateTrendingStickerSets{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTrendingStickerSets) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateTrendingStickerSets)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTrendingStickerSets) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateTrendingStickerSets))
}
