// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateForumTopicInfo Basic information about a topic in a forum chat was changed
type UpdateForumTopicInfo struct {
	Filter   filters.UpdateForumTopicInfo
	Response func(b *gotdbot.Client, u *gotdbot.UpdateForumTopicInfo) error
}

// NewUpdateForumTopicInfo creates a new UpdateForumTopicInfo
func NewUpdateForumTopicInfo(filter filters.UpdateForumTopicInfo, response func(b *gotdbot.Client, u *gotdbot.UpdateForumTopicInfo) error) *UpdateForumTopicInfo {
	return &UpdateForumTopicInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateForumTopicInfo) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateForumTopicInfo)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateForumTopicInfo) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateForumTopicInfo))
}
