// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewPreCheckoutQuery A new incoming pre-checkout query; for bots only. Contains full information about a checkout
type UpdateNewPreCheckoutQuery struct {
	Filter   filters.UpdateNewPreCheckoutQuery
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewPreCheckoutQuery) error
}

// NewUpdateNewPreCheckoutQuery creates a new UpdateNewPreCheckoutQuery
func NewUpdateNewPreCheckoutQuery(filter filters.UpdateNewPreCheckoutQuery, response func(b *gotdbot.Client, u *gotdbot.UpdateNewPreCheckoutQuery) error) *UpdateNewPreCheckoutQuery {
	return &UpdateNewPreCheckoutQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewPreCheckoutQuery) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewPreCheckoutQuery)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewPreCheckoutQuery) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewPreCheckoutQuery))
}
