// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdatePollAnswer A user changed the answer to a poll; for bots only
type UpdatePollAnswer struct {
	Filter   filters.UpdatePollAnswer
	Response func(b *gotdbot.Client, u *gotdbot.UpdatePollAnswer) error
}

// NewUpdatePollAnswer creates a new UpdatePollAnswer
func NewUpdatePollAnswer(filter filters.UpdatePollAnswer, response func(b *gotdbot.Client, u *gotdbot.UpdatePollAnswer) error) *UpdatePollAnswer {
	return &UpdatePollAnswer{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdatePollAnswer) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdatePollAnswer)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdatePollAnswer) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdatePollAnswer))
}
