// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateTextCompositionStyles The styles supported for text composition have changed
type UpdateTextCompositionStyles struct {
	Filter   filters.UpdateTextCompositionStyles
	Response func(b *gotdbot.Client, u *gotdbot.UpdateTextCompositionStyles) error
}

// NewUpdateTextCompositionStyles creates a new UpdateTextCompositionStyles
func NewUpdateTextCompositionStyles(filter filters.UpdateTextCompositionStyles, response func(b *gotdbot.Client, u *gotdbot.UpdateTextCompositionStyles) error) *UpdateTextCompositionStyles {
	return &UpdateTextCompositionStyles{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTextCompositionStyles) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateTextCompositionStyles)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTextCompositionStyles) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateTextCompositionStyles))
}
