// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateApplicationVerificationRequired A request can't be completed unless application verification is performed; for official mobile applications only.
type UpdateApplicationVerificationRequired struct {
	Filter   filters.UpdateApplicationVerificationRequired
	Response func(b *gotdbot.Client, u *gotdbot.UpdateApplicationVerificationRequired) error
}

// NewUpdateApplicationVerificationRequired creates a new UpdateApplicationVerificationRequired
func NewUpdateApplicationVerificationRequired(filter filters.UpdateApplicationVerificationRequired, response func(b *gotdbot.Client, u *gotdbot.UpdateApplicationVerificationRequired) error) *UpdateApplicationVerificationRequired {
	return &UpdateApplicationVerificationRequired{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateApplicationVerificationRequired) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateApplicationVerificationRequired)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateApplicationVerificationRequired) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateApplicationVerificationRequired))
}
