// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatRemovedFromList A chat was removed from a chat list
type UpdateChatRemovedFromList struct {
	Filter   filters.UpdateChatRemovedFromList
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatRemovedFromList) error
}

// NewUpdateChatRemovedFromList creates a new UpdateChatRemovedFromList
func NewUpdateChatRemovedFromList(filter filters.UpdateChatRemovedFromList, response func(b *gotdbot.Client, u *gotdbot.UpdateChatRemovedFromList) error) *UpdateChatRemovedFromList {
	return &UpdateChatRemovedFromList{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatRemovedFromList) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatRemovedFromList)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatRemovedFromList) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatRemovedFromList))
}
