// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatViewAsTopics A chat default appearance has changed
type UpdateChatViewAsTopics struct {
	Filter   filters.UpdateChatViewAsTopics
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatViewAsTopics) error
}

// NewUpdateChatViewAsTopics creates a new UpdateChatViewAsTopics
func NewUpdateChatViewAsTopics(filter filters.UpdateChatViewAsTopics, response func(b *gotdbot.Client, u *gotdbot.UpdateChatViewAsTopics) error) *UpdateChatViewAsTopics {
	return &UpdateChatViewAsTopics{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatViewAsTopics) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatViewAsTopics)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatViewAsTopics) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatViewAsTopics))
}
