// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatUnreadReactionCount The chat unread_reaction_count has changed
type UpdateChatUnreadReactionCount struct {
	Filter   filters.UpdateChatUnreadReactionCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatUnreadReactionCount) error
}

// NewUpdateChatUnreadReactionCount creates a new UpdateChatUnreadReactionCount
func NewUpdateChatUnreadReactionCount(filter filters.UpdateChatUnreadReactionCount, response func(b *gotdbot.Client, u *gotdbot.UpdateChatUnreadReactionCount) error) *UpdateChatUnreadReactionCount {
	return &UpdateChatUnreadReactionCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatUnreadReactionCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatUnreadReactionCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatUnreadReactionCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatUnreadReactionCount))
}
