// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateStoryPostSucceeded A story has been successfully posted
type UpdateStoryPostSucceeded struct {
	Filter   filters.UpdateStoryPostSucceeded
	Response func(b *gotdbot.Client, u *gotdbot.UpdateStoryPostSucceeded) error
}

// NewUpdateStoryPostSucceeded creates a new UpdateStoryPostSucceeded
func NewUpdateStoryPostSucceeded(filter filters.UpdateStoryPostSucceeded, response func(b *gotdbot.Client, u *gotdbot.UpdateStoryPostSucceeded) error) *UpdateStoryPostSucceeded {
	return &UpdateStoryPostSucceeded{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStoryPostSucceeded) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateStoryPostSucceeded)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStoryPostSucceeded) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateStoryPostSucceeded))
}
