// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateUnreadMessageCount Number of unread messages in a chat list has changed. This update is sent only if the message database is used
type UpdateUnreadMessageCount struct {
	Filter   filters.UpdateUnreadMessageCount
	Response func(b *gotdbot.Client, u *gotdbot.UpdateUnreadMessageCount) error
}

// NewUpdateUnreadMessageCount creates a new UpdateUnreadMessageCount
func NewUpdateUnreadMessageCount(filter filters.UpdateUnreadMessageCount, response func(b *gotdbot.Client, u *gotdbot.UpdateUnreadMessageCount) error) *UpdateUnreadMessageCount {
	return &UpdateUnreadMessageCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUnreadMessageCount) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateUnreadMessageCount)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUnreadMessageCount) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateUnreadMessageCount))
}
