// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageIsPinned The message pinned state was changed
type UpdateMessageIsPinned struct {
	Filter   filters.UpdateMessageIsPinned
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageIsPinned) error
}

// NewUpdateMessageIsPinned creates a new UpdateMessageIsPinned
func NewUpdateMessageIsPinned(filter filters.UpdateMessageIsPinned, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageIsPinned) error) *UpdateMessageIsPinned {
	return &UpdateMessageIsPinned{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageIsPinned) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageIsPinned)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageIsPinned) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageIsPinned))
}
