// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateMessageFactCheck A fact-check added to a message was changed
type UpdateMessageFactCheck struct {
	Filter   filters.UpdateMessageFactCheck
	Response func(b *gotdbot.Client, u *gotdbot.UpdateMessageFactCheck) error
}

// NewUpdateMessageFactCheck creates a new UpdateMessageFactCheck
func NewUpdateMessageFactCheck(filter filters.UpdateMessageFactCheck, response func(b *gotdbot.Client, u *gotdbot.UpdateMessageFactCheck) error) *UpdateMessageFactCheck {
	return &UpdateMessageFactCheck{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageFactCheck) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateMessageFactCheck)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageFactCheck) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateMessageFactCheck))
}
