// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatAddedToList A chat was added to a chat list
type UpdateChatAddedToList struct {
	Filter   filters.UpdateChatAddedToList
	Response func(b *gotdbot.Client, u *gotdbot.UpdateChatAddedToList) error
}

// NewUpdateChatAddedToList creates a new UpdateChatAddedToList
func NewUpdateChatAddedToList(filter filters.UpdateChatAddedToList, response func(b *gotdbot.Client, u *gotdbot.UpdateChatAddedToList) error) *UpdateChatAddedToList {
	return &UpdateChatAddedToList{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatAddedToList) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateChatAddedToList)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatAddedToList) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateChatAddedToList))
}
