// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewBusinessMessage A new message was added to a business account; for bots only
type UpdateNewBusinessMessage struct {
	Filter   filters.UpdateNewBusinessMessage
	Response func(b *gotdbot.Client, u *gotdbot.UpdateNewBusinessMessage) error
}

// NewUpdateNewBusinessMessage creates a new UpdateNewBusinessMessage
func NewUpdateNewBusinessMessage(filter filters.UpdateNewBusinessMessage, response func(b *gotdbot.Client, u *gotdbot.UpdateNewBusinessMessage) error) *UpdateNewBusinessMessage {
	return &UpdateNewBusinessMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewBusinessMessage) CheckUpdate(b *gotdbot.Client, update gotdbot.TlObject) bool {
	u, ok := update.(*gotdbot.UpdateNewBusinessMessage)
	if !ok {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewBusinessMessage) HandleUpdate(b *gotdbot.Client, update gotdbot.TlObject) error {
	return h.Response(b, update.(*gotdbot.UpdateNewBusinessMessage))
}
